-- What are the details of all cars purchased in the year 2022?
select *
from cars
join sales on sales.car_id = cars.car_id
having year(purchase_date)='2022';

-- What is the total number of cars sold by each salesperson?
select salespersons.name, count(car_id) as cars_sold
from sales, salespersons
where sales.salesman_id = salespersons.salesman_id
group by salespersons.salesman_id;

-- What is the total revenue generated by each salesperson?

select salespersons.name, sum(cars.cost_$) as revenue
from salespersons, cars, sales
where sales.salesman_id=salespersons.salesman_id and cars.car_id=sales.car_id
group by salespersons.name
order by revenue desc;

-- What are the details of the cars sold by each salesperson?

select *
from cars, sales
where cars.car_id = sales.car_id;

-- What is the total revenue generated by each car type?

select style, sum(cost_$) as revenue
from cars, sales
where sales.car_id = cars.car_id
group by style
order by revenue desc;

-- What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

select *
from cars, sales, salespersons
where sales.car_id =  cars.car_id and salespersons.salesman_id = sales.salesman_id
and salespersons.name = 'Emily Wong' and year(purchase_date) = '2021';

-- What is the total revenue generated by the sales of hatchback cars?

select style, sum(cost_$) as revenue
from cars, sales
where sales.car_id = cars.car_id and style = 'Hatchback';

-- What is the total revenue generated by the sales of SUV cars in the year 2022?

select style, sum(cost_$) as revenue
from cars
join sales on sales.car_id = cars.car_id
where style = 'SUV' and year(purchase_date) = '2022';


-- What is the name and city of the salesperson who sold the most number of cars in the year 2023?

select salespersons.name, city, count(sales.salesman_id) as sales_made
from salespersons, sales
where sales.salesman_id = salespersons.salesman_id and year(purchase_date) = '2023'
group by sales.salesman_id
order by sales_made desc limit 1;

-- What is the name and age of the salesperson who generated the highest revenue in the year 2022?

select salespersons.name, age, sum(cost_$) as revenue
from salespersons, sales, cars
where cars.car_id = sales.car_id and salespersons.salesman_id = sales.salesman_id
group by salespersons.salesman_id
order by revenue desc limit 1;


