-- What are the names of all the countries in the country table?

select distinct country_name
from country;

-- What is the total number of customers in the customers table?

select count(customer_id) as customers
from customers;

-- What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?

select round(avg(age), 2) as avg_age
from customers
where can_email='yes';

--  How many orders were made by customers aged 30 or older?

select count(order_id) as count
from orders, customers
where customers.customer_id = orders.customer_id and age > 30;

-- What is the total revenue generated by each product category?

select category, sum(price)
from baskets, products
where baskets.product_id = products.product_id
group by products.product_id;

-- What is the average price of products in the 'food' category?



--  How many orders were made in each sales channel (sales_channel column) in the orders table?

select sales_channel, count(order_id) as sales
from orders
group by sales_channel;

-- What is the date of the latest order made by a customer who can receive marketing emails?

select date_shop
from customers, orders
where orders.customer_id = customers.customer_id and can_email = 'yes'
order by date_shop desc limit 1;

-- What is the name of the country with the highest number of orders?

select country_name, count(orders.country_id) as no_of_orders
from orders, country
where country.country_id = orders.country_id
group by orders.country_id
order by no_of_orders desc limit 1;

--  What is the average age of customers who made orders in the 'vitamins' product category?

select round(avg(age), 2) as avg_age_vitamins
from baskets, orders, products, customers
where orders.order_id = baskets.order_id and products.product_id = baskets.product_id and customers.customer_id = orders.customer_id
and category = 'vitamins'
group by category